# Generated by Django 4.1.2 on 2022-11-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=254)),
                ('item_description', models.CharField(max_length=2000)),
                ('item_sprice', models.DecimalField(decimal_places=2, max_digits=100)),
                ('item_picture', models.ImageField(upload_to='')),
                ('item_auctionfinish', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_dob', models.DateField()),
                ('user_profilePicture', models.ImageField(upload_to='')),
            ],
        ),
    ]
