# Generated by Django 4.1.3 on 2022-12-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilePicture',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_personHighestBid',
            field=models.EmailField(default='tbd', max_length=254),
        ),
    ]
