# Generated by Django 4.1.3 on 2022-12-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_alter_customuser_date_of_birth'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profilePicture',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
