# Generated by Django 4.1.3 on 2022-12-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0002_customuser_custom_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='custom_username',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
