# Generated by Django 4.1.3 on 2022-12-04 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0003_customuser_custom_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='custom_username',
        ),
    ]
