# Generated by Django 4.1.3 on 2022-12-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0003_alter_item_item_personhighestbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_picture',
            field=models.ImageField(default='./auction_app_vue_frontend/src/Images/profile example.png', height_field=50, max_length=1, upload_to='./auction_app_vue_frontend/src/Images', width_field=50),
        ),
    ]
