# Generated by Django 4.1.3 on 2022-12-05 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0004_remove_customuser_custom_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserProfile',
        ),
    ]
