# Generated by Django 4.1.3 on 2022-12-05 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0004_remove_customuser_custom_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_personHighestBid',
            field=models.CharField(default='tbd', max_length=254),
            preserve_default=False,
        ),
    ]
