# Generated by Django 4.1.3 on 2022-12-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0004_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
