# Generated by Django 4.1.3 on 2022-12-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0005_item_item_personhighestbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_personHighestBid',
            field=models.CharField(default='tbd', max_length=254),
        ),
    ]
