# Generated by Django 4.1.3 on 2022-12-06 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0005_rename_user_userprofile'),
        ('auction_app', '0006_alter_item_item_personhighestbid'),
    ]

    operations = [
    ]
