# Generated by Django 4.1.3 on 2022-12-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0006_item_item_image_alter_item_item_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default=None, height_field=50, null=True, upload_to='./auction_app_vue_frontend/src/Images', width_field=50),
        ),
    ]
