# Generated by Django 4.1.3 on 2022-12-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0007_merge_20221206_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('user_dob', models.DateField()),
                ('user_profilePicture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
