# Generated by Django 4.1.3 on 2022-12-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0010_alter_item_item_auctionfinish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default=None, null=True, upload_to='./auction_app_vue_frontend/src/Images'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_personHighestBid',
            field=models.EmailField(default='tbd@tbd.tbd', max_length=254),
        ),
    ]
