# Generated by Django 4.1.3 on 2022-12-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0012_questions_answers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
        migrations.RenameModel(
            old_name='Questions',
            new_name='Question',
        ),
    ]
