# Generated by Django 4.1.3 on 2022-12-15 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction_app', '0013_rename_answers_answer_rename_questions_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='auction_app.item'),
            preserve_default=False,
        ),
    ]
